name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #- name: Build with Gradle
      #  run: ./gradlew build

      #- name: Run unit tests
      #  run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew clean build jacocoTestReport

      - name: Run unit tests
        run: ./gradlew test

      - name: Run Ktlint
        run: ./gradlew ktlint

      - name: Upload Ktlint report
        uses: actions/upload-artifact@v4
        with:
          name: Ktlint Report
          path: app/build/reports/ktlint

      - name: Publish JUnit test results
        if: always()
        uses: junit-team/junit-report-builder@v2
        with:
          report-files: "**/TEST-*.xml"

      - name: Publish HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Reports
          path: app/build/reports/tests/testDebugUnitTest/index.html
